#!/bin/bash

CONFIG_FILE="${HOME}/.config/restore.conf"
LOADING_BAR_FILE="loading_bar.sh"

source "${CONFIG_FILE}"
source "${LOADING_BAR_FILE}"

$(${USE_COMPRESSION})
COMPRESS=$?

# extract file if needed
[ "${COMPRESS}" ] &&  echo "extracting"\
  && tar -xvaf "${COMPRESSED_FILE}" "${BACKUP_DIR}" && echo "done"

IFS=$'\t'

i=0
n=$( wc -l < "${BACKUP_DIR}/${FILES_MAP}" )

[ "$n" = "0" ] && echo "no files specified in ${BACKUP_DIR}/${FILES_MAP}"\
  "nothing to do" && exit 1

echo "restoring backed up files and directories"

while read -r KEY VALUE; do
  loading_bar $i $n 40
  cp "${CP_ARGS[@]}" "${BACKUP_DIR}/${KEY}" ${VALUE}
  (( i++ ))
done < "${BACKUP_DIR}/${FILES_MAP}"

loading_bar $i $n 40
echo ""
echo "done"

# clean up remnants of decompression
[ "${COMPRESS}" ] && echo "cleaning up" && rm -r ${BACKUP_DIR}
